export const arr = [
  { name: "Pure-E", alg: "[*]" },
  { name: "Adj-E", alg: "R U R' U' [*] U' R U' R'" },
  { name: "O+", alg: "M' U' M2 U' M2 U' M' U2 M2 [*]" },
  { name: "O-", alg: "M' U' M2 U' M2 U' M' U2 M2 U' [*]" },
  { name: "W", alg: "R U' R U R U R U' R' U' R2 [*]" },
  { name: "Ba", alg: "[*] U R U R' F' R U R' U' R' F R2 U' R'" },
  { name: "Bb", alg: "R U R' U' R' F R2 U' R' [*] U R U R' F'" },
  { name: "Ca", alg: "[*] U R' U2 R U2 R' F R U R' U' R' F' R2" },
  { name: "Cb", alg: "[*] R U R' F' R U2 R' U2 R' F R U R U2 R'" },
  { name: "Da", alg: "R' U L' U2 R U' R' U2 R L U' [*]" },
  { name: "Db", alg: "R U R' F' R U R' U' R' F R2 U' R' [*]" },
  { name: "Pa", alg: "R U R' F' R U R' U' R' F R2 U' R' U' [*]" },
  { name: "Pb", alg: "[*] R U R' F' R U R' U' R' F R2 U' R'" },
  { name: "Ka", alg: "[*] x R2 D2 R U R' D2 R U' R" },
  { name: "Kb", alg: "[*] U x R' U R' D2 R U' R' D2 R2" },
  { name: "Q", alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x U [*]" },
  { name: "Sa", alg: "F R U' R' U' R U R' F' R U R' U' R' F R F' U' [*]" },
  { name: "Sb", alg: "F R U' R' U' R U R' F' R U R' U' R' F R F' [*]" },
  { name: "X", alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x [*]" },
  { name: "M", alg: "R U R' U' R' F R2 U' R' U' R U R' F' [*]" },
  { name: "Adj-C", alg: "R U R' U' R' F R2 U' R' U' R U R' F' U' [*]" },
  { name: "Diag-C", alg: "F R U' R' U' R U R' F' U' [*] U' R U R' U' R' F R F'" },
];

export const specialAlg = "Rw2 R2 U2 Rw2 R2 Uw2 Rw2 R2 Uw2";
