export const arr = [
  { name: "L1", alg: "R' U R' U2 R U' R' U R U' R2" },
  { name: "L2", alg: "R U2 R2 F2 R U R' F2 R F'" },
  { name: "L3", alg: "R U2 R' F' R U2 R' U R' F2 R" },
  { name: "L4", alg: "F R' F' R U R U' R'" },
  { name: "L5", alg: "F R U' R' U' R U R' F'" },
  { name: "L6", alg: "R U2 R' R' F R F' R U2 R'" },
  { name: "U1", alg: "R2 F2 R U R' F R2 U2 R' U' R" },
  { name: "U2", alg: "R U2 R U' R' F R' F2 U' F" },
  { name: "U3", alg: "R' U R' F R F' R U2 R' U R" },
  { name: "U4", alg: "F R' F' R U' R U' R' U2 R U' R'" },
  { name: "U5", alg: "R U' R' R' F R F' R U R' U' R U R'" },
  { name: "U6", alg: "F R U R' U' F'" },
  { name: "T1", alg: "R' U R U2 R2 F' R U' R' F2 R2" },
  { name: "T2", alg: "R' U R U2 R' R' F R F' R" },
  { name: "T3", alg: "y L' U' L U L F' L' F" },
  { name: "T4", alg: "F R U R' U' R U' R' U' R U R' F'" },
  { name: "T5", alg: "R U R' U' R' F R F'" },
  { name: "T6", alg: "F U' R U2 R' U' F2 R U R'" },
  { name: "P1", alg: "R U' R2 U R2 U R2 U' R" },
  { name: "P2", alg: "R' F2 R F' U2 R U' R' U' F" },
  { name: "P3", alg: "F R2 U' R2 U R2 U R2 F'" },
  { name: "P4", alg: "R U2 R' U' R U R' U2 R' F R F'" },
  { name: "P5", alg: "R U' R' F R' F R U R' F R" },
  { name: "P6", alg: "R' U' R' F R F' R U' R' U2 R" },
  { name: "H1", alg: "R2 U2 R' U2 R2" },
  { name: "H2", alg: "F R2 U' R2 U' R2 U R2 F'" },
  { name: "H3", alg: "R U R' U R U L' U R' U' L" },
  { name: "H4", alg: "x' U2 R U2 R2 F2 R U2 x" },
  { name: "AS1", alg: "L' U' L U' L' U2 L" },
  { name: "AS2", alg: "L' U' L U L F' L' F L' U' L U' L' U2 L" },
  { name: "AS3", alg: "F' L F L' U2 L' U2 L" },
  { name: "AS4", alg: "R U2 R' U2 R' F R F'" },
  { name: "AS5", alg: "R' F R F' R U R'" },
  { name: "AS6", alg: "R' U R U' (R2 F R F') R U R' U' R" },
  { name: "S1", alg: "R U R' U R U2 R'" },
  { name: "S2", alg: "L' U2 L U2 L F' L' F" },
  { name: "S3", alg: "F R' F' R U2 R U2 R'" },
  { name: "S4", alg: "R U R' U' R' F R F' R U R' U R U2 R'" },
  { name: "S5", alg: "L F' L' F L' U' L" },
  { name: "S6", alg: "R U R' U R' F R F' R U2 R'" },
  { name: "Adjacent", alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: "Diagonal", alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
];
