export const arr = [
  { name: "Oriented", alg: "L' U2 (R U R') U2 L" },
  { name: "Rectangle", alg: "R U' R'" },
  { name: "Rectangle", alg: "U' R' F R U R U' R' F'" },
  { name: "Snake", alg: "R2 D R' U' R D' R2" },
  { name: "Snake", alg: "(R U' R') U (R' U' R U' R' U2 R)" },
  { name: "Tank", alg: "U' (R U' R' U2) (R U' R' U2) R U R'" },
  { name: "Tank", alg: "R U R' U' R U' R'" },
  { name: "Gun (Near)", alg: "U R U' R' U R U2 R'" },
  { name: "Gun (Sides)", alg: "R U' R' U R U2 (R2 U' R2 U' R2) U2 R" },
  { name: "Gun (Back)", alg: "R U (R2 U' R2 U' R2) U2 R" },
  { name: "Gun (Far)", alg: "U R' U' R2 U' R2 U2 R" },
  { name: "Bowtie", alg: "U' (R' F2 R F2) U L' U L" },
  { name: "Bowtie", alg: "U R U2 R' (R' U' R U' R' U2 R)" },
  { name: "Bowtie", alg: "U R2 D R' U2 R D' R2" },
  { name: "Bowtie", alg: "U' L' (U R U' R') L" },
  { name: "Adjacent", alg: "U R U' R' U' R' F R U R U' R' F'" },
  { name: "Adjacent", alg: "U R U2 R'" },
  { name: "Adjacent", alg: "U' R' F' R U2 R U2 R' F" },
  { name: "Adjacent", alg: "R U' R D' R U2 R' D R U2 R" },
  { name: "Sune", alg: "R U' R' U' (R U R' U R U2 R')" },
  { name: "Sune", alg: "R U R' U' R U R' U' R U' R'" },
  { name: "Pi (Far)", alg: "R U' R' (R' U2 R U R' U R" },
  { name: "Pi (Back)", alg: "R2 D R' U R D' R' U2 R'" },
  { name: "Pi (Front)", alg: "U R U2 R' (R' U2 R U R' U R)" },
  { name: "Pi (Near)", alg: "R U' R' (R' U' R U' R' U2 R)" },
  { name: "H (Front)", alg: "U R' U L U' R2 U L' U R'" },
  { name: "H (Side)", alg: "U R U' R' U R U' R' U R U2 R'" },
];
