export const arr = [
  { name: "Solved", alg: "R U2 R' U' [*] F R' F' R" },
  { name: "U (F)", alg: "[*]" },
  { name: "U (R)", alg: "[*] U' R U R' U R U2 R'" },
  { name: "U (L)", alg: "[*] R U2 R' U' R U' R'" },
  { name: "U (B)", alg: "M [*] M'" },
  { name: "T (F)", alg: "R U R' U' R [*] R' U R U' R'" },
  { name: "T (R)", alg: "[*] R U R' U' R' F R F'" },
  { name: "T (L)", alg: "F R U' R' U' R U R' F' [*]" },
  { name: "T (B)", alg: "[*] U R U2 (R2 U' R2 U' R2) U2 R" },
  { name: "L (FR)", alg: "R' U' R [*] R' U R" },
  { name: "L (FL)", alg: "L U L' [*] L U' L'" },
  { name: "L (BR)", alg: "[*] U R' U2 R U R' U R" },
  { name: "L (BL)", alg: "[*] R' U' R U' R' U2 R" },
  { name: "Sune (FR)", alg: "M' U R U' 3Rw' [*] U R U2 R'" },
  { name: "Sune (FL)", alg: "[*] R U R' U R U2 R'" },
  { name: "Sune (BR)", alg: "L F' L' F [*] L' U L" },
  { name: "Sune (BL)", alg: "F' L' U' L U F [*]" },
  { name: "Antisune (FR)", alg: "[*] U' R U2 R' U' R U' R'" },
  { name: "Antisune (FL)", alg: "[*] R U2 (R2 U' R2 U' R2) U2 R" },
  { name: "Antisune (BR)", alg: "F R U R' U' F' [*]" },
  { name: "Antisune (BL)", alg: "R' F R F' [*] R U' R'" },
  { name: "H (FB)", alg: "[*] R2 D' R U2 R' D R U2 R" },
  { name: "H (LR)", alg: "[*] R U R' U R U' R' U R U2 R'" },
  { name: "Pi (F)", alg: "[*] U' R U2 (R2 U' R2 U' R2) U2 R" },
  { name: "Pi (R)", alg: "[*] U R' U' R U' R' U2 R" },
  { name: "Pi (L)", alg: "[*] R' U2 R U R' U R" },
  { name: "Pi (B)", alg: "[*] U' 3Rw U R' U' 3Rw' F R F'" },
];

export const specialAlg = "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'";
