export const arr = [
  { name: "L1", alg: "R U' R' U R U' R2 F' R F" },
  { name: "L2", alg: "L' U L U' L' U L2 F L' F'" },
  { name: "L3", alg: "L' U' L F L' U' L U F' L F L'" },
  { name: "L4", alg: "R U R' F' R U R' U' F R' F' R" },
  { name: "L5", alg: "R' U R2 U' R2 U' F R2 U' R'" },
  { name: "L6", alg: "R' F R2 U R' F' R U2 R'" },
  { name: "U1", alg: "F R U' R' F x F' L' U' L' U x'" },
  { name: "U2", alg: "R U' R2 F R2 U R' U' R U' R'" },
  { name: "U3", alg: "L F' L' F L F' L2 U L" },
  { name: "U4", alg: "F' U2 R U2 R' U2 F" },
  { name: "U5", alg: "F' U L F2 L' F U2 F" },
  { name: "U6", alg: "F U' R' F2 R F' U2 F'" },
  { name: "T1", alg: "R2 B2 U' R' U' R U' R' U R'" },
  { name: "T2", alg: "L' U L2 F' L' U' L' U2 L" },
  { name: "T3", alg: "R' F' R2 U R' F' R U R'" },
  { name: "T4", alg: "R U R' F R U R' F U' R U' R'" },
  { name: "T5", alg: "F L F' L2 U' L U L' U' L" },
  { name: "T6", alg: "F' R' F R2 U R' U' R U R'" },
  { name: "P1", alg: "F U' R' F R U' F2 R U R'" },
  { name: "P2", alg: "R' F R2 U' R2 F R" },
  { name: "P3", alg: "F R' F U' F2 R U R" },
  { name: "P4", alg: "R U' R' U R U' R' F R U' R'" },
  { name: "P5", alg: "L F' L' F L F' L2 U' L U L' U L" },
  { name: "P6", alg: "R' F R F' R' F R2 U R' U' R U' R'" },
  { name: "H1", alg: "R' F R2 U' R' F R U R' F'" },
  { name: "H2", alg: "F' U R U' R2 F2 R U' F" },
  { name: "H3", alg: "R U R' F' R U R' U' R U R'" },
  { name: "H4", alg: "R' F R F' U2 F R U2 R' F" },
  { name: "AS1", alg: "R' F R2 U R' F' U' R U' R'" },
  { name: "AS2", alg: "R U' R' F' U' F2 R U' R'" },
  { name: "AS3", alg: "F L F' L2 U' L U F' L F L'" },
  { name: "AS4", alg: "F' R U R' U' R U R2 F' R" },
  { name: "AS5", alg: "R U' R2 F R U' R' F R F'" },
  { name: "AS6", alg: "L' U L U' L' U L U L F L' F'" },
  { name: "S1", alg: "L F' L2 U' L F U L' U L" },
  { name: "S2", alg: "L' U L F U F2 L' U L" },
  { name: "S3", alg: "F' R' F R2 U R' U' F R' F' R" },
  { name: "S4", alg: "F L' U' L U L' U' L2 F L'" },
  { name: "S5", alg: "L' U L2 F' L' U L F' L' F" },
  { name: "S6", alg: "R U' R' U R U' R' U' R' F' R F" },
  { name: "Solved", alg: "R' U R' U' R' F R2 U' R' U' R U R' F' R2" },
  { name: "Adjacent", alg: "R2 U' R2 U2 F2 U' R2" },
  { name: "Diagonal", alg: "R U' R' U' R' F2 U' R U R" },
];
