export const arr = [
  { name: "L1", alg: "R' U2 (R U R' U') R U R' U' R U R' U R" },
  { name: "L2", alg: "R' U2 R' D' R U2 R' D R2" },
  { name: "L3", alg: "R U2 R D R' U2 R D' R2" },
  { name: "L4", alg: "F R' F' r U R U' r'" },
  { name: "L5", alg: "x R' U R D' R' U' R D x'" },
  { name: "L6", alg: "R' U' (R U R') F' R U R' U' R' F R2" },
  { name: "U1", alg: "R' U' R U' R' U2 R R U R' U R U2 R'" },
  { name: "U2", alg: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R" },
  { name: "U3", alg: "R2 D R' U2 R D' R' U2 R'" },
  { name: "U4", alg: "F R U' R' U R U R' U R U' R' F'" },
  { name: "U5", alg: "R2 D' R U2 R' D R U2 R" },
  { name: "U6", alg: "R2 D' R U R' D R U R U' R' U' R" },
  { name: "T1", alg: "R U2 R' U' R U' R' R' U2 R U R' U R" },
  { name: "T2", alg: "R' U R U2 R' L' U R U' L" },
  { name: "T3", alg: "y l' U' L U l F' L' F" },
  { name: "T4", alg: "y2 F R U R' U' R U' R' U' R U R' F'" },
  { name: "T5", alg: "y' r U R' U' r' F R F'" },
  { name: "T6", alg: "R' U R2 D r' U2 r D' R2 U' R" },
  { name: "P1", alg: "R U2 (R2 U' R2 U' R2) U2 R" },
  { name: "P2", alg: "R' F2 R U2 R U2 R' F2 U' R U' R'" },
  { name: "P3", alg: "R' U' F' R U R' U' R' F R2 U2 R' U2 R" },
  { name: "P4", alg: "R U R' U' R' F R2 U R' U' R U R' U' F'" },
  { name: "P5", alg: "R U' L' U R' U L U L' U L" },
  { name: "P6", alg: "R2 D' R U R' D R U R U' R' U R U R' U R" },
  { name: "H1", alg: "R U R' U R U' R' U R U2 R'" },
  { name: "H2", alg: "F R U' R' U R U2 R' U' R U R' U' F'" },
  { name: "H3", alg: "R U R' U R U L' U R' U' L" },
  { name: "H4", alg: "F R U R' U' R U R' U' R U R' U' F'" },
  { name: "AS1", alg: "L' U' L U' L' U2 L" },
  { name: "AS2", alg: "R' U2 F' R U R' U' R' F R2 U R' U R" },
  { name: "AS3", alg: "R2 D R' U2 R D' R2 U' R U' R'" },
  { name: "AS4", alg: "R' U' R U' R2 D' R U2 R' D R2" },
  { name: "AS5", alg: "L' U R U' L U R'" },
  { name: "AS6", alg: "y2 R U' R' U2 R U' R' U2 R' D' R U R' D R" },
  { name: "S1", alg: "R U R' U R U2 R'" },
  { name: "S2", alg: "L' U2 L U2 R U' L' U L R'" },
  { name: "S3", alg: "R2 D' R U2 R' D R2 U R' U R" },
  { name: "S4", alg: "y' R U R' U R U' R D R' U' R D' R2" },
  { name: "S5", alg: "R U' L' U R' U' L" },
  { name: "S6", alg: "F' R U2 R' U2 R' F2 R U R U' R' F'" },
];
